// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOgQNgWk2Ucf7hxpGMSkfHPwFHzfMiho4',
    appId: '1:815596252512:web:9f1d09e7702f4f6682c205',
    messagingSenderId: '815596252512',
    projectId: 'fiestafinder2006',
    authDomain: 'fiestafinder2006.firebaseapp.com',
    databaseURL: 'https://fiestafinder2006-default-rtdb.firebaseio.com',
    storageBucket: 'fiestafinder2006.firebasestorage.app',
    measurementId: 'G-YVE0GKE6XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplKfDOViThXhmiyyQqTDM4PS_roM-VU0',
    appId: '1:815596252512:android:61da1c694d6477d182c205',
    messagingSenderId: '815596252512',
    projectId: 'fiestafinder2006',
    databaseURL: 'https://fiestafinder2006-default-rtdb.firebaseio.com',
    storageBucket: 'fiestafinder2006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0co4okZhY6PR5U8xsaLzNzQUOnz0ItiM',
    appId: '1:815596252512:ios:56fcc3d3ada6c4a682c205',
    messagingSenderId: '815596252512',
    projectId: 'fiestafinder2006',
    databaseURL: 'https://fiestafinder2006-default-rtdb.firebaseio.com',
    storageBucket: 'fiestafinder2006.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}